### ISSUE TITLE
The database we are using is outdated.

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/running-rhino-server#1]
I logged in our current Running Rhino database in this repo using the following credentials:

## Database URL
DBURL thecity.sfsu.edu

## Database name
DBName csc63101

## Database user name
DBUsername csc63101

## Database user password
DBPassword csc631_01

The following query does not work because the `hidden` column does not exist under the `species` or `species_id` tables:

## The current query to get plants:

 `String query = ""
                + "SELECT * "
                + "FROM `species` s JOIN `species_nodes` sn ON s.`species_id` = sn.`species_id` "
                + "WHERE `organism_type` = 1 AND `hidden` = 0 "
                + "ORDER BY s.`species_id`, sn.`node_id`";`

### Current columns:
                    `plantType = new PlantType(species_id);
                    plantType.setName(rs.getString("name"));
                    plantType.setOrganismType(rs.getInt("organism_type"));
                    plantType.setCost(rs.getInt("cost"));
                    plantType.setDescription(rs.getString("description"));
                    plantType.setCategory(rs.getString("category"));
                    plantType.setAvgBiomass(rs.getInt("max_biomass"));
                    plantType.setWaterNeedFrequency(rs.getInt("water_need_frequency"));
                    plantType.setLightNeedFrequency(rs.getInt("light_need_frequency"));
                    plantType.setGrowRadius(rs.getFloat("grow_radius"));
                    plantType.setCarryingCapacity(rs.getFloat("carrying_capacity"));
                    plantType.setTrophicLevel(rs.getFloat("trophic_level"));
                    plantType.setGrowthRate(rs.getFloat("growth_rate"));
                    plantType.setModelID(rs.getInt("model_id"));
                    plantType.setHealChance(rs.getFloat("heal_chance"));
                    plantType.setGroupCapacity(rs.getInt("group_capacity"));`

### Columns in `species` and `speciesId` under `thecity.sfsu.edu`:

`species_id, name, organism_type, cost, description, category, biomass, diet_type, carrying_capacity, metabolism, trophic_level, growth_rate, model_id, unlock, species_id, node_id, distribution`

## Missing columns: 

`hidden, max_biomass, water_need_frequency, light_need_frequency, group_capacity`

**Comment by niculistana** [comment]
@jensvdh What is hunvil's github account?

**Comment by jensvdh** [comment]
Her username is Hunvil. Although I'm not sure if she is related to Running Rhino

**Comment by niculistana** [comment]
I added hunvil to this organization. She wrote the database code.

**Comment by niculistana** [comment]
Yikes... it turns out that the dummy database in `smurf.sfsu.edu` is the one that's currently updated. I will go ahead and migrate the database schema from smurf to `thecity.sfsu.edu`

**Comment by niculistana** [comment]
I switched the `db.conf` file to:

#Database URL
DBURL smurf.sfsu.edu	


#Database name
DBName deBuggerWeb


#Database user name
DBUsername deBuggerWeb


#Database user password
DBPassword deBugger

And I was able to retrieve data. So if Yoon is alright with migrating data from smurf to thecity, I will go ahead and do that.

**Comment by jensvdh** [comment]
Yeah that works. Can you share these findings with the database team?

You guys are still working on integrating with wob-server repository right?

**Comment by niculistana** [comment]
@jensvdh I posted some items on ilearn regarding this.

**Comment by niculistana** [comment]
@hunvil which database did you use when writing the database classes?
