### ISSUE TITLE
Is the running rhino server supposed to subclass the shared server?

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/running-rhino-server#2]
I know @jensvdh discussed this during class, but as far as implementation goes, do we sublcass the running rhino server from the shared server or do we keep everything separate?

Although subclassing can be a good idea for the long run, I think we should keep them all separate for now and have next semester refactor the code. There isn't enough time for our milestones to cover both the shared and running rhino server.

**Comment by jensvdh** [comment]
What do you mean with subclassing it?

I should start its own JAR and boot as a minigame. If that makes sense?

**Comment by niculistana** [comment]
@jensvdh I was confused with having multiple GameServer.java classes from `shared.core` and `rr.core` packages. It makes sense to me that we have to start its own jar and boot as a minigame. Thank you for clarifying.
